services:
  workforce-planner:
    image: ghcr.io/sitscholl/meteo-service:latest
    ports:
      - "8000:8000"
    volumes:
      # Mount config directory for persistence
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    container_name: meteo-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s