TIMEZONE = 'Europe/Rome'

sbr_colmap = {
    "mg4": {
        "id": "4",
        "kuerzel_de": "T2m",
        "kuerzel": "T2m",
        "bezeichnung": "Lufttemperatur 2m",
        "berechnung": "mittel",
        "unterer_gw": "-30",
        "oberer_gw": "60",
        "einheit": "degC",
        "MesswertSpalteNeu": "mg4",
        "MesswertSpalte": "Value4",
        "aufloesung": "0.1",
        "graph_type": "curve",
        "graph_color": "#f4cf0c",
        "connected_Axis": "&deg;C"
    }, 
    "mg12": {
        "id": "12",
        "kuerzel_de": "TB -25cm",
        "kuerzel": "TB -25cm",
        "bezeichnung": "Bodentemperatur -25cm",
        "berechnung": "mittel",
        "unterer_gw": "-20",
        "oberer_gw": "40",
        "einheit": "degC",
        "MesswertSpalteNeu": "mg12",
        "MesswertSpalte": "Value12",
        "aufloesung": "0.1",
        "graph_type": "curve",
        "graph_color": "#b16002",
        "connected_Axis": "&deg;C"
    }, 
    "mg1": {
        "id": "1",
        "kuerzel_de": "Tt",
        "kuerzel": "Tt",
        "bezeichnung": "Trockentemperatur 60cm",
        "berechnung": "mittel",
        "unterer_gw": "-30",
        "oberer_gw": "80",
        "einheit": "degC",
        "MesswertSpalteNeu": "mg1",
        "MesswertSpalte": "Value1",
        "aufloesung": "0.1",
        "graph_type": "curve",
        "graph_color": "#32CD32",
        "connected_Axis": "&deg;C"
    }, 
    "mg2": {
        "id": "2",
        "kuerzel_de": "Tf",
        "kuerzel": "Tf",
        "bezeichnung": "Feuchttemperatur 60cm",
        "berechnung": "mittel",
        "unterer_gw": "-30",
        "oberer_gw": "80",
        "einheit": "degC",
        "MesswertSpalteNeu": "mg2",
        "MesswertSpalte": "Value2",
        "aufloesung": "0.1",
        "graph_type": "curve",
        "graph_color": "#FF0000",
        "connected_Axis": "&deg;C"
    }, 
    "mg3": {
        "id": "3",
        "kuerzel_de": "RL",
        "kuerzel": "RL",
        "bezeichnung": "Relative Luftfeuchtigkeit",
        "berechnung": "mittel",
        "unterer_gw": "0",
        "oberer_gw": "100",
        "einheit": "%",
        "MesswertSpalteNeu": "mg3",
        "MesswertSpalte": "Value3",
        "aufloesung": "0.1",
        "graph_type": "curve",
        "graph_color": "#4a8283",
        "connected_Axis": "%"
    }, 
    "mg6": {
        "id": "6",
        "kuerzel_de": "Wind",
        "kuerzel": "Wind",
        "bezeichnung": "Windgeschwindigkeit",
        "berechnung": "mittel",
        "unterer_gw": "0",
        "oberer_gw": "40",
        "einheit": "m*s-1",
        "MesswertSpalteNeu": "mg6",
        "MesswertSpalte": "Value6",
        "aufloesung": "0.1",
        "graph_type": "area",
        "graph_color": "#89898932",
        "connected_Axis": "m*s-1"
    }, 
    "mg19": {
        "id": "19",
        "kuerzel_de": "Wg  max",
        "kuerzel": "Wg  max",
        "bezeichnung": "Max. Windgeschwindigkeit i Messintervall",
        "berechnung": "max",
        "unterer_gw": "0",
        "oberer_gw": "40",
        "einheit": "m*s-1",
        "MesswertSpalteNeu": "mg19",
        "MesswertSpalte": "Value19",
        "aufloesung": "0.1",
        "graph_type": "spike",
        "graph_color": "#676767",
        "connected_Axis": "m*s-1"
    }, 
    "mg9": {
        "id": "9",
        "kuerzel_de": "Nied.",
        "kuerzel": "Nied.",
        "bezeichnung": "Niederschlag",
        "berechnung": "summe",
        "unterer_gw": "0",
        "oberer_gw": "25",
        "einheit": "mm",
        "MesswertSpalteNeu": "mg9",
        "MesswertSpalte": "Value9",
        "aufloesung": "0.1",
        "graph_type": "bar",
        "graph_color": "#00B6FF32",
        "connected_Axis": "mm"
    },
    "mg10": {
        "id": "10",
        "kuerzel_de": "Ber.",
        "kuerzel": "Ber.",
        "bezeichnung": "Beregnung aktiv",
        "berechnung": "max",
        "unterer_gw": "0",
        "oberer_gw": "1",
        "einheit": "Ein/Aus",
        "MesswertSpalteNeu": "mg10",
        "MesswertSpalte": "Value10",
        "aufloesung": "1",
        "graph_type": "bar",
        "graph_color": "#0008FF",
        "connected_Axis": "Ein/Aus"
    },
    "mg8": {
        "id": "8",
        "kuerzel_de": "Bn",
        "kuerzel": "Bn",
        "bezeichnung": "Blattnässe",
        "berechnung": "mittel",
        "unterer_gw": "0",
        "oberer_gw": "100",
        "einheit": "%",
        "MesswertSpalteNeu": "mg8",
        "MesswertSpalte": "Value8",
        "aufloesung": "0.1",
        "graph_type": "curve",
        "graph_color": "#9932CC",
        "connected_Axis": "%"
    },
    "mg56": {
        "id": "56",
        "kuerzel_de": "Nied. sum",
        "kuerzel": "Nied. sum",
        "bezeichnung": "Niederschlag Summe",
        "berechnung": "mittel",
        "unterer_gw": None,
        "oberer_gw": None,
        "einheit": "mm",
        "MesswertSpalteNeu": "mg56",
        "MesswertSpalte": "NiederschlagsMenge",
        "aufloesung": "0.1",
        "graph_type": "curve",
        "graph_color": "#51b5a6",
        "connected_Axis": "mm"
    },
    "mg50": {
        "id": "50",
        "kuerzel_de": "T2m avg",
        "kuerzel": "T2m avg",
        "bezeichnung": "Durchschnittliche Lufttemperatur 2m",
        "berechnung": "mittel",
        "unterer_gw": "-30",
        "oberer_gw": "60",
        "einheit": "degC",
        "MesswertSpalteNeu": "mg50",
        "MesswertSpalte": "T2mMedia",
        "aufloesung": "0.1",
        "graph_type": "curve",
        "graph_color": "#FF6B42",
        "connected_Axis": "&deg;C"
    },
    "mg51": {
        "id": "51",
        "kuerzel_de": "Ausf.",
        "kuerzel": "Ausf.",
        "bezeichnung": "Stationsausfall",
        "berechnung": "keine",
        "unterer_gw": "0",
        "oberer_gw": "1",
        "einheit": "",
        "MesswertSpalteNeu": None,
        "MesswertSpalte": None,
        "aufloesung": "0",
        "graph_type": "bar",
        "graph_color": "#E80000",
        "connected_Axis": ""
    },
    "mg52": {
        "id": "52",
        "kuerzel_de": "BMp",
        "kuerzel": "BMp",
        "bezeichnung": "Beginn Millsperiode",
        "berechnung": "keine",
        "unterer_gw": "0",
        "oberer_gw": "1",
        "einheit": "",
        "MesswertSpalteNeu": "mg52",
        "MesswertSpalte": "InfektionsStatus",
        "aufloesung": "1",
        "graph_type": "bar",
        "graph_color": "#5cd65c",
        "connected_Axis": ""
    }, 
    "mg53": {
        "id": "53",
        "kuerzel_de": "LMp",
        "kuerzel": "LMp",
        "bezeichnung": "leichte",
        "berechnung": "keine",
        "unterer_gw": "0",
        "oberer_gw": "1",
        "einheit": "",
        "MesswertSpalteNeu": None,
        "MesswertSpalte": "InfektionsStatus",
        "aufloesung": "0",
        "graph_type": "bar",
        "graph_color": "#ecec13",
        "connected_Axis": ""
    }, 
    "mg54": {
        "id": "54",
        "kuerzel_de": "MMp",
        "kuerzel": "MMp",
        "bezeichnung": "mittlere",
        "berechnung": "keine",
        "unterer_gw": "0",
        "oberer_gw": "1",
        "einheit": "",
        "MesswertSpalteNeu": None,
        "MesswertSpalte": "InfektionsStatus",
        "aufloesung": "0",
        "graph_type": "bar",
        "graph_color": "#FF7B00",
        "connected_Axis": ""
    }, 
    "mg55": {
        "id": "55",
        "kuerzel_de": "SMp",
        "kuerzel": "SMp",
        "bezeichnung": "schwere",
        "berechnung": "keine",
        "unterer_gw": "0",
        "oberer_gw": "1",
        "einheit": "",
        "MesswertSpalteNeu": None,
        "MesswertSpalte": "InfektionsStatus",
        "aufloesung": "0",
        "graph_type": "bar",
        "graph_color": "#B22222",
        "connected_Axis": ""
    }
}